@startgantt Time Planning

[Team Forming] requires 7 days
[Project Brief] requires 3 days
[Requirements] requires 7 days
[Planning] requires 5 days
[Architecture] requires 4 days
[Test] requires 28 days
[Code] requires 30 days
[Documentation] requires 40 days

Project starts 2024-09-26

[Team Forming] starts 2024-09-26
[Project Brief] starts at 2024-09-30
[Planning] starts at [Project Brief]'s end
[Planning review 1] starts 2024-10-17
[Planning review 2] starts 2024-10-24 
[Planning review 3] starts 2024-10-31 
[Planning review 4] starts 2024-11-07  
[Requirements] starts 2024-09-30
[Architecture] starts at [Requirements]'s end
[Code] starts at [Architecture]'s end
[Test] starts 3 days after [Code]'s start
[Documentation] ends 2024-11-11
[Code Review 1] starts 2024-10-18
[Code Review 2] starts 2024-10-25
[Code Review 3] starts 2024-11-1
[Code Review 4] starts 2024-11-8

@endgantt